### ISSUE TITLE
Maven 3.3.3

### ISSUE THREAD

**Issue by mvlach** [springfuse/project-lombok-example#1]
Hi, I can't compile this project...

Using Java 8 and Maven 3.3.3

Thnanks Mila

[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ projectlombok ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ projectlombok ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /private/tmp/mila/project-lombok-example/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ projectlombok ---
[INFO] Compiling 12 source files to /private/tmp/mila/project-lombok-example/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /private/tmp/mila/project-lombok-example/src/main/java/com/springfuse/blog/projectlombok/advanced/LogExample.java:[8,8] error: cannot find symbol
[ERROR]  class LogExample
/private/tmp/mila/project-lombok-example/src/main/java/com/springfuse/blog/projectlombok/advanced/ValExample.java:[10,22] error: incompatible types: ArrayList<String> cannot be converted to val
[ERROR] /private/tmp/mila/project-lombok-example/src/main/java/com/springfuse/blog/projectlombok/advanced/ValExample.java:[12,19] error: cannot find symbol
[ERROR]  variable example of type val
/private/tmp/mila/project-lombok-example/src/main/java/com/springfuse/blog/projectlombok/advanced/ValExample.java:[14,15] error: incompatible types: val cannot be converted to List<String>
[INFO] 4 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.786 s
[INFO] Finished at: 2015-10-15T11:02:30+02:00
[INFO] Final Memory: 16M/182M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project projectlombok: Compilation failure: Compilation failure:
[ERROR] /private/tmp/mila/project-lombok-example/src/main/java/com/springfuse/blog/projectlombok/advanced/LogExample.java:[8,8] error: cannot find symbol
[ERROR] class LogExample
[ERROR] /private/tmp/mila/project-lombok-example/src/main/java/com/springfuse/blog/projectlombok/advanced/ValExample.java:[10,22] error: incompatible types: ArrayList<String> cannot be converted to val
[ERROR] /private/tmp/mila/project-lombok-example/src/main/java/com/springfuse/blog/projectlombok/advanced/ValExample.java:[12,19] error: cannot find symbol
[ERROR] variable example of type val
[ERROR] /private/tmp/mila/project-lombok-example/src/main/java/com/springfuse/blog/projectlombok/advanced/ValExample.java:[14,15] error: incompatible types: val cannot be converted to List<String>
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by framiere** [comment]
Hi, I updated the versions (https://github.com/springfuse/project-lombok-example/commit/79ab23cf8247a650af94f51b9e51143097601325). You should be able to play with the code now. Enjoy !
